name: CI/CD (Docker Hub -> Cloud Run)

on:
  push:
    branches: [ main ]

env:
  BACKEND_SERVICE: blog-backend
  FRONTEND_SERVICE: blog-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      backend_image: ${{ steps.out.outputs.backend_image }}
      frontend_image: ${{ steps.out.outputs.frontend_image }}
    steps:
      - uses: actions/checkout@v4

      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tags
        id: out
        run: |
          echo "backend_image=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/blog-backend:${GITHUB_SHA}" >> $GITHUB_OUTPUT
          echo "frontend_image=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/blog-frontend:${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Build & push backend (server/)
        uses: docker/build-push-action@v6
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: |
            ${{ steps.out.outputs.backend_image }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/blog-backend:latest

      - name: Build & push frontend (root)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.out.outputs.frontend_image }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/blog-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy backend to Cloud Run
        run: |
          gcloud run deploy "${{ env.BACKEND_SERVICE }}" \
            --region "${{ secrets.GCP_REGION }}" \
            --image "${{ needs.build-and-push.outputs.backend_image }}" \
            --port 8080 \
            --allow-unauthenticated \
            --update-env-vars "MONGODB_URI=${{ secrets.MONGODB_URI }},JWT_SECRET=${{ secrets.JWT_SECRET }}"

      - name: Deploy frontend to Cloud Run
        run: |
          gcloud run deploy "${{ env.FRONTEND_SERVICE }}" \
            --region "${{ secrets.GCP_REGION }}" \
            --image "${{ needs.build-and-push.outputs.frontend_image }}" \
            --port 8080 \
            --allow-unauthenticated

      - name: Print service URLs
        run: |
          BURL=$(gcloud run services describe "${{ env.BACKEND_SERVICE }}" --region "${{ secrets.GCP_REGION }}" --format='value(status.url)')
          FURL=$(gcloud run services describe "${{ env.FRONTEND_SERVICE }}" --region "${{ secrets.GCP_REGION }}" --format='value(status.url)')
          echo "Backend:  $BURL"
          echo "Frontend: $FURL"
