name: CI/CD (Docker Hub -> Cloud Run)

on:
  push:
    branches: [ main ]

env:
  REGION: ${{ secrets.GCP_REGION }}
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  DH_USER: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      backend_image: ${{ steps.out.outputs.backend_image }}
      frontend_image: ${{ steps.out.outputs.frontend_image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Backend image
      - name: Build & push backend
        uses: docker/build-push-action@v6
        with:
          context: ./server
          push: true
          tags: |
            docker.io/${{ env.DH_USER }}/blog-backend:${{ github.sha }}
            docker.io/${{ env.DH_USER }}/blog-backend:latest

      # Frontend image
      - name: Build & push frontend
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            docker.io/${{ env.DH_USER }}/blog-frontend:${{ github.sha }}
            docker.io/${{ env.DH_USER }}/blog-frontend:latest

      - name: Output image tags
        id: out
        run: |
          echo "backend_image=docker.io/${DH_USER}/blog-backend:${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
          echo "frontend_image=docker.io/${DH_USER}/blog-frontend:${GITHUB_SHA}" >> "$GITHUB_OUTPUT"

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Deploy backend (Cloud Run)
        run: |
          gcloud run deploy blog-backend \
            --region "${REGION}" \
            --image "${{ needs.build-and-push.outputs.backend_image }}" \
            --port 8080 \
            --allow-unauthenticated \
            --update-env-vars MONGODB_URI="${{ secrets.MONGODB_URI }}",JWT_SECRET="${{ secrets.JWT_SECRET }}"

      - name: Deploy frontend (Cloud Run)
        run: |
          gcloud run deploy blog-frontend \
            --region "${REGION}" \
            --image "${{ needs.build-and-push.outputs.frontend_image }}" \
            --port 8080 \
            --allow-unauthenticated

      - name: Show service URLs
        run: |
          echo "Backend:  $(gcloud run services describe blog-backend  --region "${REGION}" --format='value(status.url)')"
          echo "Frontend: $(gcloud run services describe blog-frontend --region "${REGION}" --format='value(status.url)')"
