name: CI/CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  id-token: write # harmless even if unused; needed if you switch to WI later

env:
  IMAGE_TAG: ${{ github.sha }}
  # Docker Hub repo names
  BACKEND_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-starter-backend
  FRONTEND_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-starter-frontend
  # Cloud Run (optional)
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  BACKEND_SERVICE: blog-backend
  FRONTEND_SERVICE: blog-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect app paths
        id: detect
        shell: bash
        run: |
          detect_path() {
            local name="$1"; shift
            for p in "$@"; do
              if [ -d "$p" ] && ls "$p"/Dockerfile* >/dev/null 2>&1; then
                echo "$name=$p" >> "$GITHUB_OUTPUT"
                return 0
              fi
            done
            echo "$name=" >> "$GITHUB_OUTPUT"
          }
          # Candidates (expand as you like)
          detect_path backend backend apps/backend api server services/backend packages/backend
          detect_path frontend frontend apps/frontend web client ui services/frontend packages/frontend

      - name: Show detected contexts
        run: |
          echo "BACKEND_CTX='${{ steps.detect.outputs.backend }}'"
          echo "FRONTEND_CTX='${{ steps.detect.outputs.frontend }}'"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true

      # ---------- BACKEND ----------
      - name: Build & push backend
        if: ${{ steps.detect.outputs.backend != '' }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ steps.detect.outputs.backend }}
          push: true
          tags: |
            ${{ env.BACKEND_IMAGE }}:${{ env.IMAGE_TA
