name: CI/CD (Docker Hub -> Cloud Run)

on:
  push:
    branches: [ main ]
    tags: [ 'v*', '*.*.*' ]  # optional tag deploys

env:
  BACKEND_SERVICE: blog-backend
  FRONTEND_SERVICE: blog-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      backend_image: ${{ steps.out.outputs.backend_image }}
      frontend_image: ${{ steps.out.outputs.frontend_image }}
    steps:
      - uses: actions/checkout@v4

      - name: Decide image tag
        id: tag
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "IMAGE_TAG=${GITHUB_REF_NAME}" >> "$GITHUB_ENV"
          else
            SHORT_SHA="${GITHUB_SHA::7}"
            echo "IMAGE_TAG=sha-${SHORT_SHA}" >> "$GITHUB_ENV"
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend image
        run: docker build -t docker.io/${{ secrets.DOCKERHUB_USERNAME }}/blog-backend:${IMAGE_TAG} server
      - name: Push backend image
        run: docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/blog-backend:${IMAGE_TAG}

      - name: Build frontend image
        run: docker build -t docker.io/${{ secrets.DOCKERHUB_USERNAME }}/blog-frontend:${IMAGE_TAG} .
      - name: Push frontend image
        run: docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/blog-frontend:${IMAGE_TAG}

      - name: Set outputs
        id: out
        run: |
          echo "backend_image=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/blog-backend:${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "frontend_image=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/blog-frontend:${IMAGE_TAG}" >> $GITHUB_OUTPUT

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: cloud-run-deploy
      cancel-in-progress: true
    steps:
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Set region
        run: gcloud config set run/region "${{ secrets.GCP_REGION }}"

      - name: Deploy backend
        env:
          IMG: ${{ needs.build-and-push.outputs.backend_image }}
        run: |
          gcloud run deploy "${{ env.BACKEND_SERVICE }}" \
            --image "$IMG" \
            --port 8080 \
            --allow-unauthenticated \
            --update-env-vars MONGODB_URI="${{ secrets.MONGODB_URI }}",JWT_SECRET="${{ secrets.JWT_SECRET }}"

      - name: Deploy frontend
        env:
          IMG: ${{ needs.build-and-push.outputs.frontend_image }}
        run: |
          gcloud run deploy "${{ env.FRONTEND_SERVICE }}" \
            --image "$IMG" \
            --port 8080 \
            --allow-unauthenticated

      - name: Show service URLs
        run: |
          echo "Backend:  $(gcloud run services describe ${{ env.BACKEND_SERVICE }} --format='value(status.url)')"
          echo "Frontend: $(gcloud run services describe ${{ env.FRONTEND_SERVICE }} --format='value(status.url)')"
