name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: skilful-webbing-385501

      - name: Deploy backend
        run: |
          echo "=== Deploying backend ==="
          echo "Using image: docker.io/halefcaetano13/fullstack-starter-backend:latest"
          gcloud run deploy blog-backend \
            --image=docker.io/halefcaetano13/fullstack-starter-backend:latest \
            --region=us-central1 --platform=managed --quiet
          echo "Backend Service URL:"
          gcloud run services describe blog-backend \
            --region=us-central1 --platform=managed --format='value(status.url)'
          echo "Latest revision:"
          gcloud run revisions list --service=blog-backend --region=us-central1 --limit=1

      - name: Deploy frontend
        run: |
          echo "=== Deploying frontend ==="
          echo "Using image: docker.io/halefcaetano13/fullstack-starter-frontend:latest"
          gcloud run deploy blog-frontend \
            --image=docker.io/halefcaetano13/fullstack-starter-frontend:latest \
            --region=us-central1 --platform=managed --quiet
          echo "Frontend Service URL:"
          gcloud run services describe blog-frontend \
            --region=us-central1 --platform=managed --format='value(status.url)'
          echo "Latest revision:"
          gcloud run revisions list --service=blog-frontend --region=us-central1 --limit=1
