name: CI/CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  # not strictly required for key-based auth, but harmless if you later switch to Workload Identity
  id-token: write

env:
  IMAGE_TAG: ${{ github.sha }}
  # Docker Hub repo names
  BACKEND_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-starter-backend
  FRONTEND_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-starter-frontend
  # Cloud Run (optional)
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  BACKEND_SERVICE: blog-backend
  FRONTEND_SERVICE: blog-frontend
  # Helper flag so we can conditionally run GCP steps
  HAS_GCP: ${{ secrets.GCP_SA_KEY != '' && secrets.GCP_PROJECT_ID != '' && secrets.GCP_REGION != '' }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect app paths
        id: detect
        shell: bash
        run: |
          detect_path() {
            # first arg is the output name; remaining are candidate dirs
            local name="$1"
            shift
            for p in "$@"; do
              if [ -d "$p" ] && ls "$p"/Dockerfile* >/dev/null 2>&1; then
                echo "$name=$p" >> "$GITHUB_OUTPUT"
                return 0
              fi
            done
            echo "$name=" >> "$GITHUB_OUTPUT"
          }
          # Add/modify candidates as needed
          detect_path backend backend apps/backend api server services/backend packages/backend
          detect_path frontend frontend apps/frontend web client ui services/frontend packages/frontend
          echo "Detected BACKEND_CTX='${{ steps.detect.outputs.backend }}'"
          echo "Detected FRONTEND_CTX='${{ steps.detect.outputs.frontend }}'"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true

      # ---------- BACKEND ----------
      - name: Build & push backend
        if: ${{ steps.detect.outputs.backend != '' }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ steps.detect.outputs.backend }}
          push: true
          tags: |
            ${{ env.BACKEND_IMAGE }}:${{ env.IMAGE_TAG }}
            ${{ env.BACKEND_IMAGE }}:latest
          cache-from: type=gha,scope=backend
          cache-to: type=gha,mode=max,scope=backend

      # ---------- FRONTEND ----------
      - name: Build & push frontend
        if: ${{ steps.detect.outputs.frontend != '' }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ steps.detect.outputs.frontend }}
          push: true
          tags: |
            ${{ env.FRONTEND_IMAGE }}:${{ env.IMAGE_TAG }}
            ${{ env.FRONTEND_IMAGE }}:latest
          cache-from: type=gha,scope=frontend
          cache-to: type=gha,mode=max,scope=frontend

      # ---------- Cloud Run deploy (optional) ----------
      - name: Google Auth (key JSON)
        if: ${{ env.HAS_GCP == 'true' }}
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set gcloud defaults
        if: ${{ env.HAS_GCP == 'true' }}
        run: |
          gcloud config set project "${PROJECT_ID}"
          gcloud config set run/region "${REGION}"

      - name: Deploy backend to Cloud Run
        if: ${{ env.HAS_GCP == 'true' && steps.detect.outputs.backend != '' }}
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.BACKEND_SERVICE }}
          region: ${{ env.REGION }}
          image: docker.io/${{ env.BACKEND_IMAGE }}:${{ env.IMAGE_TAG }}

      - name: Deploy frontend to Cloud Run
        if: ${{ env.HAS_GCP == 'true' && steps.detect.outputs.frontend != '' }}
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.FRONTEND_SERVICE }}
          region: ${{ env.REGION }}
          image: docker.io/${{ env.FRONTEND_IMAGE }}:${{ env.IMAGE_TAG }}
