name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}


env:
  IMAGE_TAG: ${{ github.sha }}
  REGION: ${{ secrets.GCP_REGION }}
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  BACKEND_SERVICE: blog-backend
  FRONTEND_SERVICE: blog-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ---- DOCKER HUB LOGIN (uses secrets) ----
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true

      # ---- BUILD & PUSH BACKEND ----
      - name: Build backend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-starter-backend:${{ env.IMAGE_TAG }} ./backend
          docker tag  ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-starter-backend:${{ env.IMAGE_TAG }} ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-starter-backend:latest
      - name: Push backend image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-starter-backend:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-starter-backend:latest

      # ---- BUILD & PUSH FRONTEND ----
      - name: Build frontend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-starter-frontend:${{ env.IMAGE_TAG }} ./client
          docker tag  ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-starter-frontend:${{ env.IMAGE_TAG }} ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-starter-frontend:latest
      - name: Push frontend image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-starter-frontend:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-starter-frontend:latest

      # ---- AUTH TO GCP ----
      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        run: |
          gcloud config set project $PROJECT_ID
          gcloud config set run/region $REGION

      # ---- DEPLOY BACKEND TO CLOUD RUN ----
      - name: Deploy backend to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.BACKEND_SERVICE }}
          region: ${{ env.REGION }}
          image: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/fullstack-starter-backend:${{ env.IMAGE_TAG }}

      # ---- DEPLOY FRONTEND TO CLOUD RUN ----
      - name: Deploy frontend to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.FRONTEND_SERVICE }}
          region: ${{ env.REGION }}
          image: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/fullstack-starter-frontend:${{ env.IMAGE_TAG }}
