name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: halefcaetano13
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push backend image
        run: |
          docker build -t halefcaetano13/backend:latest ./server
          docker push halefcaetano13/backend:latest

      - name: Build & push frontend image
        run: |
          docker build -t halefcaetano13/frontend:latest .
          docker push halefcaetano13/frontend:latest

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy backend to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: blog-backend
          region: us-central1
          image: halefcaetano13/backend:latest
          project_id: skilful-webbing-385501

      - name: Deploy frontend to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: blog-frontend
          region: us-central1
          image: halefcaetano13/frontend:latest
          project_id: skilful-webbing-385501
